[tools]
bun            = "1.3.2"
node           = "22.21.1"
"pipx:checkov" = "3.2.492"
terraform      = "1.6.6"
terraform-docs = "0.20.0"
tflint         = "0.59.1"
uv             = "0.9.8"

[settings.npm]
bun = true

[settings.pipx]
uvx = true
