[tools]
bun            = "1.3.5"
node           = "24.12.0"
"pipx:checkov" = "3.2.497"
terraform      = "1.6.6"
terraform-docs = "0.21.0"
tflint         = "0.60.0"
uv             = "0.9.21"

[settings.npm]
bun = true

[settings.pipx]
uvx = true
