[tools]
bun            = "1.3.4"
node           = "24.11.1"
"pipx:checkov" = "3.2.495"
terraform      = "1.6.6"
terraform-docs = "0.20.0"
tflint         = "0.60.0"
uv             = "0.9.17"

[settings.npm]
bun = true

[settings.pipx]
uvx = true
