[tools]
bun            = "1.3.9"
node           = "24.13.1"
"pipx:checkov" = "3.2.504"
terraform      = "1.6.6"
terraform-docs = "0.21.0"
tflint         = "0.61.0"
uv             = "0.10.2"

[settings.npm]
bun = true

[settings.pipx]
uvx = true
